//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YzuSchool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YzuSchool()
        {
            this.YzuMajors = new HashSet<YzuMajor>();
        }
    
        public int SchoolID { get; set; }
        public string SchoolName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YzuMajor> YzuMajors { get; set; }
    }
}
